from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

import pytest

from glucorag.ingest.importers import (
    HIGH_SENTINEL,
    LOW_SENTINEL,
    ImportFormatError,
    parse_cgm_csv,
)

KOLKATA = ZoneInfo("Asia/Kolkata")

LIBRE = """\
Glucose Data,Generated on,05-01-2024 09:14 UTC,Generated by,A Person
Device,Serial Number,Device Timestamp,Record Type,Historic Glucose mmol/L,Scan Glucose mmol/L
FreeStyle LibreLink,ABC,05-01-2024 08:00,0,5.6,
FreeStyle LibreLink,ABC,05-01-2024 08:07,1,,5.9
FreeStyle LibreLink,ABC,05-01-2024 08:15,0,6.1,
FreeStyle LibreLink,ABC,04-01-2024 23:45,0,4.0,
"""


def test_libreview_uses_historic_rows_converts_mmol_and_sorts():
    p = parse_cgm_csv(LIBRE, KOLKATA)
    assert (p.format, p.unit) == ("libreview", "mmol/L")
    # Scan row ignored; ascending order; mmol/L -> mg/dL.
    assert [v for _, v in p.readings] == [72.1, 100.9, 109.9]
    assert p.readings[0][0].tzinfo == KOLKATA


def test_ambiguous_day_month_picks_the_contiguous_reading():
    # Days <= 12 parse as both m-d and d-m; only d-m keeps the rows within one day.
    rows = ["timestamp,glucose"] + [
        f"{d:02d}-01-2024 {h:02d}:00,{100 + h}" for d, h in ((5, 22), (5, 23), (6, 0))
    ]
    p = parse_cgm_csv("\n".join(rows), KOLKATA)
    times = [t.replace(tzinfo=None) for t, _ in p.readings]
    assert times == [datetime(2024, 1, 5, 22), datetime(2024, 1, 5, 23), datetime(2024, 1, 6, 0)]
    assert (p.date_order, p.date_ambiguous) == ("dmy", False)  # contiguity decided it


def _same_day(day_month: str) -> str:
    return "timestamp,glucose\n" + "\n".join(
        f"{day_month}-2026 {h:02d}:{m:02d},{100 + h}" for h in (7, 8) for m in (0, 30)
    )


def test_same_day_file_is_read_as_ending_nearest_to_now_and_flagged():
    # 06-10: 6 Oct (dmy) or 10 Jun (mdy). Both span 1.5 h; today is 6 Oct.
    now = datetime(2026, 10, 6, 9, 0, tzinfo=KOLKATA)
    p = parse_cgm_csv(_same_day("06-10"), KOLKATA, now=now)
    assert p.readings[-1][0] == datetime(2026, 10, 6, 8, 30, tzinfo=KOLKATA)
    assert (p.date_order, p.date_ambiguous) == ("dmy", True)
    # On 11 Jun, the same text reads as 10 Jun: 6 Oct would be in the future.
    june = parse_cgm_csv(_same_day("06-10"), KOLKATA, now=datetime(2026, 6, 11, tzinfo=KOLKATA))
    assert june.readings[-1][0].month == 6 and june.date_order == "mdy"


def test_explicit_date_order_overrides_and_is_not_ambiguous():
    now = datetime(2026, 10, 6, 9, 0, tzinfo=KOLKATA)
    p = parse_cgm_csv(_same_day("06-10"), KOLKATA, date_order="mdy", now=now)
    assert p.readings[0][0].month == 6 and (p.date_order, p.date_ambiguous) == ("mdy", False)


def test_dates_only_one_order_can_read_are_not_ambiguous():
    now = datetime(2026, 10, 30, tzinfo=KOLKATA)
    p = parse_cgm_csv(_same_day("25-10"), KOLKATA, now=now)  # month 25 is impossible
    assert (p.date_order, p.date_ambiguous) == ("dmy", False)


def test_dexcom_egv_rows_with_low_high_sentinels_and_iso_times():
    text = (
        "Index,Timestamp (YYYY-MM-DDThh:mm:ss),Event Type,Event Subtype,Glucose Value (mg/dL)\n"
        "1,,FirstName,,\n"
        "2,2024-03-01T10:00:00,EGV,,Low\n"
        "3,2024-03-01T10:05:00,EGV,,90\n"
        "4,2024-03-01T10:10:00,Calibration,,95\n"
        "5,2024-03-01T10:15:00,EGV,,High\n"
    )
    p = parse_cgm_csv(text, KOLKATA)
    assert p.format == "dexcom" and p.unit == "mg/dL"
    assert [v for _, v in p.readings] == [LOW_SENTINEL, 90.0, HIGH_SENTINEL]


def test_generic_csv_detects_mmol_from_values_and_keeps_explicit_offsets():
    text = "time,value\n2024-02-01T08:00:00+00:00,5.5\n2024-02-01T08:15:00Z,6.0\nbad,7\n"
    p = parse_cgm_csv(text, KOLKATA)
    assert p.unit == "mmol/L" and p.skipped_rows == 1
    assert p.readings[1][0] - p.readings[0][0] == timedelta(minutes=15)
    assert p.readings[0][0].utcoffset() == timedelta(0)


def test_unit_override_wins_over_detection():
    p = parse_cgm_csv("time,value\n2024-02-01T08:00:00,5.5\n", KOLKATA, unit="mg/dL")
    assert p.readings[0][1] == 5.5


@pytest.mark.parametrize(
    "text", ["hello,world\n1,2\n", "timestamp,glucose\n,\n", "timestamp,glucose\nnot a date,5\n"]
)
def test_unusable_files_raise_a_clear_error(text):
    with pytest.raises(ImportFormatError):
        parse_cgm_csv(text, KOLKATA)
